# Url master node
spark.master    spark://spark-master:7077
spark.eventLog.enabled  true
spark.eventLog.dir  /opt/spark/events
spark.history.fs.logDirectory   /opt/spark/eventsasda

# set aws parameters
spark.hadoop.fs.s3a.endpoint  http://minio:9000
spark.hadoop.fs.s3a.impl    org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.access.key  testuser
spark.hadoop.fs.s3a.secret.key  password
spark.hadoop.fs.s3a.path.style.access  true

spark.hadoop.fs.permissions.unmask-mode 002
