"""Initital db, create Account db

Revision ID: 35822d1c57f4
Revises: 
Create Date: 2025-11-29 21:52:15.286527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '35822d1c57f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('signin_name', sa.VARCHAR(), nullable=False),
    sa.Column('salt', sa.VARCHAR(), nullable=False),
    sa.Column('pwd_hash', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('personal_identifier', sa.VARCHAR(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_claim',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_claim_principal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('system_claims_lookup', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_claims', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('account_private_information',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('special_name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('post_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('preference', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('secret_qas', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('emailverification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activation_key', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emailverification')
    op.drop_table('account_private_information')
    op.drop_table('account_claim_principal')
    op.drop_table('account_claim')
    op.drop_table('account')
    # ### end Alembic commands ###
